version: "3.9"

services:
  redis_server:
    image: redis
    command: redis-server
    ports:
      - 6378:6379
  web:
    build: .
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - redis-server
    depends_on:
      - redis-server